"""Planned ExECT field-family primitive sketches (Card 11 backlog).

These records are metadata-only. They document intended primitives for sparse
S2–S4 families before implementation and model-backed promotion work.
"""

from __future__ import annotations

from clinical_extraction.primitives import PrimitiveMetadata

PLANNED_EXECT_FAMILY_PRIMITIVES: tuple[PrimitiveMetadata, ...] = (
    PrimitiveMetadata(
        primitive_id="exect.investigation.surface_bridge.v1",
        name="ExECT investigation surface bridge",
        dataset="exect_v2",
        field_families=["investigation"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw investigation prediction surface plus optional note text.",
        output_contract=(
            "Modality-plus-result canonical strings such as mri normal or eeg abnormal."
        ),
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Clinical prose such as mri brain normal may differ from gold mri normal.",
            "S4 unknown guards for planned scans are a separate repair primitive.",
        ],
        implementation_refs=["src/clinical_extraction/programs/exect_s2.py"],
    ),
    PrimitiveMetadata(
        primitive_id="exect.investigation.planned_scan_guard.v1",
        name="ExECT planned investigation guard",
        dataset="exect_v2",
        field_families=["investigation"],
        clinical_operation="repair",
        knowledge_sources=["temporal_rules", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Investigation prediction with note cues for planned or unavailable results.",
        output_contract=(
            "Unknown or abstention when the note only supports a planned or unavailable scan."
        ),
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Do not treat future-tense scan plans as completed normal or abnormal results.",
        ],
        implementation_refs=["src/clinical_extraction/programs/exect_s4.py"],
    ),
    PrimitiveMetadata(
        primitive_id="exect.comorbidity.overlap_policy.v1",
        name="ExECT comorbidity overlap policy bridge",
        dataset="exect_v2",
        field_families=["comorbidity"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw comorbidity predictions plus note text for aetiology framing.",
        output_contract=(
            "Benchmark-facing comorbidity labels with cause-versus-comorbidity overlap policy."
        ),
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "EpilepsyCause and PatientHistory gold are independent; the scorer does not deduplicate across families.",
            "Prefer epilepsy_cause for aetiology framing and comorbidity for ongoing history when both apply.",
        ],
        implementation_refs=["docs/exect_s3_phase1_overlap_policy.md"],
    ),
    PrimitiveMetadata(
        primitive_id="exect.birth_development.cui_phrase_bridge.v1",
        name="ExECT birth history CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["birth_development"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw birth-history prediction surface.",
        output_contract="Affirmed CUIPhrase surfaces such as born normally.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Very sparse validation support; paraphrase mismatch is common.",
            "BirthHistory and EpilepsyCause may both receive overlapping phrases such as perinatal insult.",
        ],
        implementation_refs=[
            "src/clinical_extraction/datasets/exect.py",
            "src/clinical_extraction/programs/exect_s3.py",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.onset.cui_phrase_bridge.v1",
        name="ExECT onset CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["onset"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw onset prediction surface plus optional note text.",
        output_contract="Affirmed CUIPhrase onset surfaces; age and year attributes are not benchmark labels.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Onset gold may overlap diagnosis and seizure-type CUIPhrases; families score independently.",
            "Do not move seizure-type labels into onset unless the note supports an onset framing.",
        ],
        implementation_refs=[
            "src/clinical_extraction/datasets/exect.py",
            "src/clinical_extraction/programs/exect_s3.py",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.epilepsy_cause.cui_phrase_bridge.v1",
        name="ExECT epilepsy cause CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["epilepsy_cause"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw epilepsy-cause prediction surface plus optional note text.",
        output_contract="Affirmed CUIPhrase aetiology surfaces with cause-versus-comorbidity policy.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Same phrase may score in both epilepsy_cause and comorbidity when gold supports both.",
            "Do not infer cause from diagnosis subtype alone.",
        ],
        implementation_refs=["docs/exect_s3_phase1_overlap_policy.md"],
    ),
    PrimitiveMetadata(
        primitive_id="exect.when_diagnosed.cui_phrase_bridge.v1",
        name="ExECT when-diagnosed CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["when_diagnosed"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw when-diagnosed prediction surface plus optional note text.",
        output_contract="Affirmed CUIPhrase timing surfaces such as epilepsy at diagnosis age.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Timing age and year attributes are not benchmark labels in Phase 1.",
            "Duplicate predictions across diagnosis and when_diagnosed are expected until prompt policy is defined.",
        ],
        implementation_refs=["src/clinical_extraction/programs/exect_s3.py"],
    ),
    PrimitiveMetadata(
        primitive_id="exect.family_history.cui_phrase_bridge.v1",
        name="ExECT family history CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["family_history"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw family-history prediction surface.",
        output_contract="Affirmed CUIPhrase family-history surfaces.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Not yet a primary S1/S4 interleaving target; defer until higher-signal probes settle.",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.social_history.cui_phrase_bridge.v1",
        name="ExECT social history CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["social_history"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw patient or social-history prediction surface.",
        output_contract="Affirmed CUIPhrase patient-history surfaces.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Published Table 1 uses Patient History; local scoring may use social_history naming.",
            "Overlap with comorbidity is possible and families score independently.",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.driving.cui_phrase_bridge.v1",
        name="ExECT driving status CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["driving"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw driving-status prediction surface.",
        output_contract="Affirmed CUIPhrase driving surfaces.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Sparse family; design only until S4 frequency and temporality probes settle.",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.pregnancy.cui_phrase_bridge.v1",
        name="ExECT pregnancy status CUIPhrase bridge",
        dataset="exect_v2",
        field_families=["pregnancy"],
        clinical_operation="benchmark_bridge",
        knowledge_sources=["controlled_vocabulary", "benchmark_label_policy", "gold_audit_policy"],
        hybrid_balance_class=["H1_post_deterministic"],
        interleaving_positions=["post"],
        control_modes=["posthoc_correction"],
        input_contract="Raw pregnancy-status prediction surface.",
        output_contract="Affirmed CUIPhrase pregnancy surfaces.",
        compatible_experiment_arms=["H1"],
        status="planned",
        caveats=[
            "Sparse family; design only until higher-signal S1/S4 probes settle.",
        ],
    ),
    PrimitiveMetadata(
        primitive_id="exect.sections.family_spans.v1",
        name="ExECT section family span candidates",
        dataset="exect_v2",
        field_families=["multi_family"],
        clinical_operation="candidate_generation",
        knowledge_sources=["regex_rules", "gold_audit_policy"],
        hybrid_balance_class=[
            "H2_pre_deterministic",
            "H4_deterministic_first_llm_adjudicates",
        ],
        interleaving_positions=["pre"],
        control_modes=["soft_hint"],
        input_contract="ExECT note text with section headers or family-scoped spans.",
        output_contract="Section-anchored candidate spans for family-filtered extraction arms.",
        compatible_experiment_arms=["H2", "H4"],
        status="planned",
        caveats=[
            "Section filtering is not automatically promotable; preserve full-note baselines.",
        ],
    ),
)
