"""Gan S0 variant, prompt, and stage-graph routing."""
from __future__ import annotations

from dataclasses import dataclass

GAN_FREQUENCY_S0_FIELD = "seizure_frequency_number"
GAN_FREQUENCY_S0_SCHEMA_LEVEL = "gan_frequency_s0"
GAN_CONTEXT_POLICY_FULL_NOTE = "full_note"
GAN_CONTEXT_POLICY_FULL_NOTE_PLUS_DETERMINISTIC_TEMPORAL_CANDIDATES = (
    "full_note_plus_deterministic_temporal_candidates"
)
GAN_CONTEXT_POLICY_DETERMINISTIC_TEMPORAL_CANDIDATES_ONLY = (
    "deterministic_temporal_candidates_only"
)
GAN_FREQUENCY_S0_RETRIEVAL_EMPTY_CANDIDATES_NOTE_STUB = (
    "[No deterministic temporal frequency evidence windows were retrieved. "
    "Adjudicate using temporal_candidates below; if empty, prefer "
    "'no seizure frequency reference' or 'unknown' per Gan policy.]"
)

GAN_FREQUENCY_S0_VARIANT = "gan_frequency_s0_single_pass"
GAN_FREQUENCY_S0_DIRECT_VARIANT = "gan_frequency_s0_direct_single_pass"
GAN_FREQUENCY_S0_VERIFY_REPAIR_VARIANT = "gan_frequency_s0_direct_verify_repair"
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT = (
    "gan_frequency_s0_temporal_candidates_verify_repair"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_temporal_candidates_single_pass"
)
GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_llm_temporal_candidates_single_pass"
)
GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_hybrid_temporal_candidates_single_pass"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_verify_repair"
)
GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT = (
    "gan_frequency_s0_llm_temporal_candidates_verify_repair"
)
GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_VERIFY_REPAIR_VARIANT = (
    "gan_frequency_s0_temporal_event_table_verify_repair"
)
GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_temporal_event_table_single_pass"
)
GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT = (
    "gan_frequency_s0_multiple_answer_det_selector"
)
GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT = (
    "gan_frequency_s0_seeded_multiple_answer_det_selector"
)
GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_VARIANT = (
    "gan_frequency_s0_explicit_reason_code_adjudicator"
)
GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_VARIANT = (
    "gan_frequency_s0_special_class_target_selector"
)
GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_VARIANT = (
    "gan_frequency_s0_candidate_ranking_target_selector"
)
GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_VARIANT = (
    "gan_frequency_s0_support_aware_target_selector"
)
GAN_FREQUENCY_S0_REACT_TEMPORAL_TOOLS_VARIANT = (
    "gan_frequency_s0_react_temporal_tools"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_GUARDS_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_det_guards"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_EVIDENCE_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_det_evidence"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONFIRM_ONLY_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_confirm_only"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_NO_GUARDS_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_verify_repair_no_guards"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_VARIANT = (
    "gan_frequency_s0_temporal_candidates_adjudicate_constrained_verifier"
)
GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_date_events_candidates_single_pass"
)
GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_llm_date_events_candidates_single_pass"
)
GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_hybrid_date_events_candidates_single_pass"
)
GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_tool_date_resolver_single_pass"
)
GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_VARIANT = (
    "gan_frequency_s0_entity_tags_date_events_single_pass"
)

GAN_FREQUENCY_S0_VERIFY_REPAIR_PROMPT_VERSION = (
    "gan_frequency_s0_direct_verify_repair_v2_4"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_verify_repair_v1_1"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_adjudicate_constrained_verifier_v1_1"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_1"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_CANONICAL_EXAMPLES_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_2_canonical_examples"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_SLOT_PAYLOAD_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_3_slot_payload"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_ERROR_TAXONOMY_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_4_error_taxonomy_policy"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_COMPACT_HIERARCHY_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_5_compact_hierarchy"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_TARGETED_EXAMPLES_MIN7_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_6_targeted_examples_min7"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_EXACT_POLICY_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_7_qwen_exact_policy"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_SCHEMA_VALIDITY_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_8_qwen_schema_validity"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_HYBRID_RESOLUTION_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_9_qwen_hybrid_resolution"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_UNKNOWN_OVERUSE_GUARD_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_single_pass_v1_5_unknown_overuse_guard"
)
GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_PROMPT_VERSION = (
    "gan_frequency_s0_llm_temporal_candidates_v1_1"
)
GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_llm_temporal_candidates_single_pass_v1_1"
)
GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_hybrid_temporal_candidates_single_pass_v1_1"
)
GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_adjudicate_verify_repair_v1_1"
)
GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_PROMPT_VERSION = (
    "gan_frequency_s0_llm_temporal_candidates_verify_repair_v1_1"
)
GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_event_table_verify_repair_v1_0"
)
GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_event_table_single_pass_v1_0"
)
GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION = (
    "gan_frequency_s0_multiple_answer_det_selector_v1_0"
)
GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION = (
    "gan_frequency_s0_seeded_multiple_answer_det_selector_v1_0"
)
GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_PROMPT_VERSION = (
    "gan_frequency_s0_explicit_reason_code_adjudicator_v1_0"
)
GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_PROMPT_VERSION = (
    "gan_frequency_s0_special_class_target_selector_v1_0"
)
GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_PROMPT_VERSION = (
    "gan_frequency_s0_candidate_ranking_target_selector_v1_0"
)
GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_PROMPT_VERSION = (
    "gan_frequency_s0_support_aware_target_selector_v1_0"
)
GAN_FREQUENCY_S0_REACT_TEMPORAL_TOOLS_PROMPT_VERSION = (
    "gan_frequency_s0_react_temporal_tools_v1_1"
)
GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_date_events_candidates_v1"
)
GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_V1_2_GUARDRAILS_PROMPT_VERSION = (
    "gan_frequency_s0_date_events_candidates_v1_2_guardrails"
)
GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_V1_2B_SCHEMA_GUARD_ONLY_PROMPT_VERSION = (
    "gan_frequency_s0_date_events_candidates_v1_2b_schema_guard_only"
)
GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_llm_date_events_v1"
)
GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_hybrid_date_events_v1"
)
GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_tool_date_resolver_v1"
)
GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_PROMPT_VERSION = (
    "gan_frequency_s0_entity_tags_v1"
)
GAN_FREQUENCY_S0_SYNTHESIS_PROMPT_VERSION = "gan_frequency_s0_synthesis_v1"
GAN_FREQUENCY_S0_DIRECT_GUARDRAILS_PROMPT_VERSION = (
    "gan_frequency_s0_direct_guardrails_v2_2"
)
GAN_FREQUENCY_S0_SYNTHESIS_PORT_TEMPORAL_PROMPT_VERSION = (
    "gan_frequency_s0_synthesis_v1_port_temporal_v1"
)
GAN_FREQUENCY_S0_GUARDRAILS_PORT_TEMPORAL_PROMPT_VERSION = (
    "gan_frequency_s0_guardrails_v2_2_port_temporal_v1"
)
GAN_FREQUENCY_S0_EVIDENCE_OPTIONAL_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_verify_repair_evidence_optional_v1"
)
GAN_FREQUENCY_S0_EVIDENCE_SPAN_CHECK_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_verify_repair_evidence_span_check_v1"
)
GAN_FREQUENCY_S0_ADJUDICATE_VERIFY_REPAIR_SPAN_CHECK_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_adjudicate_verify_repair_span_check_v1"
)
GAN_FREQUENCY_S0_CONFIRM_ONLY_VERIFIER_PROMPT_VERSION = (
    "gan_frequency_s0_temporal_candidates_confirm_only_v1_1"
)
GAN_FREQUENCY_S0_SCORER = "gan_frequency_deterministic_v1"

GAN_FREQUENCY_S0_STAGE_GRAPH_BY_VARIANT = {
    GAN_FREQUENCY_S0_DIRECT_VARIANT: "g1_direct",
    GAN_FREQUENCY_S0_VERIFY_REPAIR_VARIANT: "g2_extract_repair",
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: "g2_candidates_adjudicate",
    GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: "g2_candidates_adjudicate",
    GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_GUARDS_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_EVIDENCE_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONFIRM_ONLY_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_NO_GUARDS_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT: (
        "g3_candidates_extract_repair"
    ),
    GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT: (
        "g2_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_VARIANT: (
        "g4_reason_code_adjudicator"
    ),
    GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_VARIANT: (
        "g7_special_class_target_selector"
    ),
    GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_VARIANT: (
        "g10_candidate_ranking_target_selector"
    ),
    GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_VARIANT: (
        "g15_support_aware_target_selector"
    ),
    GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        "g3_date_events_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        "g3_date_events_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        "g3_date_events_candidates_adjudicate"
    ),
    GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_VARIANT: (
        "g2_tool_date_resolve_adjudicate"
    ),
    GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_VARIANT: (
        "g4_entity_tags_date_events_candidates_adjudicate"
    ),
}


GAN_FREQUENCY_S0_DEFAULT_PROMPT_BY_VARIANT = {
    GAN_FREQUENCY_S0_VARIANT: "gan_frequency_s0_v1",
    GAN_FREQUENCY_S0_DIRECT_VARIANT: GAN_FREQUENCY_S0_DIRECT_GUARDRAILS_PROMPT_VERSION,
    GAN_FREQUENCY_S0_VERIFY_REPAIR_VARIANT: GAN_FREQUENCY_S0_VERIFY_REPAIR_PROMPT_VERSION,
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_VERIFY_REPAIR_VARIANT: (
        "gan_frequency_s0_v1"
    ),
    GAN_FREQUENCY_S0_REACT_TEMPORAL_TOOLS_VARIANT: "gan_frequency_s0_v1",
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT: (
        GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT: (
        GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT: (
        GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_VARIANT: (
        GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_VARIANT: (
        GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_VARIANT: (
        GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_VARIANT: (
        GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_GUARDS_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_EVIDENCE_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONFIRM_ONLY_VARIANT: (
        GAN_FREQUENCY_S0_CONFIRM_ONLY_VERIFIER_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_NO_GUARDS_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_VARIANT: (
        GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_PROMPT_VERSION
    ),
    GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_VARIANT: (
        GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_PROMPT_VERSION
    ),
}


@dataclass(frozen=True)
class GanS0VariantSpec:
    program_variant: str
    default_prompt_version: str
    stage_graph_id: str | None = None


GAN_FREQUENCY_S0_VARIANT_SPECS = {
    variant: GanS0VariantSpec(
        program_variant=variant,
        default_prompt_version=default_prompt_version,
        stage_graph_id=GAN_FREQUENCY_S0_STAGE_GRAPH_BY_VARIANT.get(variant),
    )
    for variant, default_prompt_version in GAN_FREQUENCY_S0_DEFAULT_PROMPT_BY_VARIANT.items()
}


def gan_frequency_s0_variant_spec(program_variant: str) -> GanS0VariantSpec | None:
    return GAN_FREQUENCY_S0_VARIANT_SPECS.get(program_variant)


def default_gan_frequency_s0_prompt_version(program_variant: str) -> str:
    spec = gan_frequency_s0_variant_spec(program_variant)
    if spec is not None:
        return spec.default_prompt_version
    return "gan_frequency_s0_v1"


def stage_graph_id_for_program_variant(program_variant: str) -> str | None:
    spec = gan_frequency_s0_variant_spec(program_variant)
    if spec is not None:
        return spec.stage_graph_id
    return GAN_FREQUENCY_S0_STAGE_GRAPH_BY_VARIANT.get(program_variant)


__all__ = [
    "GAN_CONTEXT_POLICY_DETERMINISTIC_TEMPORAL_CANDIDATES_ONLY",
    "GAN_CONTEXT_POLICY_FULL_NOTE",
    "GAN_CONTEXT_POLICY_FULL_NOTE_PLUS_DETERMINISTIC_TEMPORAL_CANDIDATES",
    "GAN_FREQUENCY_S0_ADJUDICATE_VERIFY_REPAIR_SPAN_CHECK_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_CANDIDATE_RANKING_TARGET_SELECTOR_VARIANT",
    "GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_SUPPORT_AWARE_TARGET_SELECTOR_VARIANT",
    "GAN_FREQUENCY_S0_CONFIRM_ONLY_VERIFIER_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_V1_2_GUARDRAILS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_V1_2B_SCHEMA_GUARD_ONLY_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_DEFAULT_PROMPT_BY_VARIANT",
    "GAN_FREQUENCY_S0_DIRECT_GUARDRAILS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_DIRECT_VARIANT",
    "GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_ENTITY_TAGS_DATE_EVENTS_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_EVIDENCE_OPTIONAL_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_EVIDENCE_SPAN_CHECK_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_EXPLICIT_REASON_CODE_ADJUDICATOR_VARIANT",
    "GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_SPECIAL_CLASS_TARGET_SELECTOR_VARIANT",
    "GAN_FREQUENCY_S0_FIELD",
    "GAN_FREQUENCY_S0_GUARDRAILS_PORT_TEMPORAL_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_HYBRID_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_HYBRID_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_LLM_DATE_EVENTS_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_LLM_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT",
    "GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT",
    "GAN_FREQUENCY_S0_REACT_TEMPORAL_TOOLS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_REACT_TEMPORAL_TOOLS_VARIANT",
    "GAN_FREQUENCY_S0_RETRIEVAL_EMPTY_CANDIDATES_NOTE_STUB",
    "GAN_FREQUENCY_S0_SCHEMA_LEVEL",
    "GAN_FREQUENCY_S0_SCORER",
    "GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_SEEDED_MULTIPLE_ANSWER_DET_SELECTOR_VARIANT",
    "GAN_FREQUENCY_S0_STAGE_GRAPH_BY_VARIANT",
    "GAN_FREQUENCY_S0_SYNTHESIS_PORT_TEMPORAL_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_SYNTHESIS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONFIRM_ONLY_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_CONSTRAINED_VERIFIER_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_EVIDENCE_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_DET_GUARDS_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_NO_GUARDS_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_ADJUDICATE_VERIFY_REPAIR_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_CANONICAL_EXAMPLES_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_COMPACT_HIERARCHY_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_ERROR_TAXONOMY_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_EXACT_POLICY_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_HYBRID_RESOLUTION_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_QWEN_SCHEMA_VALIDITY_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_SLOT_PAYLOAD_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_TARGETED_EXAMPLES_MIN7_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_UNKNOWN_OVERUSE_GUARD_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_CANDIDATES_VERIFY_REPAIR_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_TEMPORAL_EVENT_TABLE_VERIFY_REPAIR_VARIANT",
    "GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_TOOL_DATE_RESOLVER_SINGLE_PASS_VARIANT",
    "GAN_FREQUENCY_S0_VARIANT",
    "GAN_FREQUENCY_S0_VARIANT_SPECS",
    "GAN_FREQUENCY_S0_VERIFY_REPAIR_PROMPT_VERSION",
    "GAN_FREQUENCY_S0_VERIFY_REPAIR_VARIANT",
    "GanS0VariantSpec",
    "default_gan_frequency_s0_prompt_version",
    "gan_frequency_s0_variant_spec",
    "stage_graph_id_for_program_variant",
]
